### ISSUE TITLE
Pick-Pocketing Mobs = Infinite Mob Drops

### ISSUE THREAD

**Issue by TheVisionaryOne** [Quarris/PickPocketer#1]
Love the concept of this mod, but there's one glaring issue with it for survival purposes. If you sneak up behind a mob, you can steal their mob drops from the auto-generated loot table, exit their inventory, steal their mob drops again, and repeat. You can essentially get infinite...anything as long as it comes from a mob's loot table, and you're able to stand behind them for a couple of seconds without them noticing you.

At the very least, there should be some sort of config option to disable this infinite loot table loophole, or a feature to disable the auto-generated loot pool all together. Maybe if there was a way to whitelist specific mobs for the loot pool, or even configure a custom loot pool for them, that would be cool.

It just doesn't make much sense for a player to be able to walk up behind a cow, and farm infinite meat and leather from it...just because the cow doesn't see them... 😛

**Comment by Quarris** [comment]
Serious question, did you try to play the mod? Because the loot is only supposed to be generated on the first time and then saved. If thats not happening then thats a bug.
Edit: custom loot tables are coming in the close future

**Comment by Quarris** [comment]
Okay so I did mess something up afterall. I'll fix it soon.
